### ISSUE TITLE
Create dummy information page

### ISSUE THREAD

**Issue by borangoher** [borangoher/frontend-demo#4]
- [ ] Create dummy info page and provide dummy content.
- ~~Utilize dummy AJAX calls.~~

**Comment by ozgunbal** [comment]
@borangoher  It would be better to separate AJAX calls. It can be moved to another issue. Requirements:
- Your api-like methods should be asynchronous
- You can use internal API-like methods to check login validation(username and password)
- You can send your form with another method
- If you need to connect real api, only api logic would be changed, calls from component are not.
